version: "3"
services:
  api: 
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=2cfe3f70f7daf95bdbd75fbc5facdd5e5932bc25d233e623732e7a1f5a419052
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30  
