name: CI/CD FastAPI

on: [push]

jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout de branch
      - uses: actions/checkout@v2
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
